import jQuery from "jquery"

require("./theme/js/jquery")
require("./theme/js/jquery.calendario")
require("./theme/js/jquery.hotspot")
require("./theme/js/jquery.mousewheel.min")
// require("./theme/js/functions")


// require("./theme/js/chart-utils")
// require("./theme/js/chart")
// require("./theme/js/events-data")
// require("./theme/js/holder")
// require("./theme/js/intersection-observer")
// require("./theme/js/plugins")
// require("./theme/js/plugins.accordions")
// require("./theme/js/plugins.ajaxform")
// require("./theme/js/plugins.ajaxportfolio")
// require("./theme/js/plugins.animations")
// require("./theme/js/plugins.carousel")
// require("./theme/js/plugins.cookie")
// require("./theme/js/plugins.countdown")
// require("./theme/js/plugins.counter")
// require("./theme/js/plugins.dataclasses")
// require("./theme/js/plugins.dataheight")
// require("./theme/js/plugins.dribble")
// require("./theme/js/plugins.easing")
// require("./theme/js/plugins.flexslider")
// require("./theme/js/plugins.form")
// require("./theme/js/plugins.gmap")
// require("./theme/js/plugins.gridfilter")
// require("./theme/js/plugins.hashchange")
// require("./theme/js/plugins.hoveranimation")
// require("./theme/js/plugins.imagesloaded")
// require("./theme/js/plugins.infinitescroll")
// require("./theme/js/plugins.isotope")
// require("./theme/js/plugins.jpaginate")
// require("./theme/js/plugins.plugins.lazyload")

